# Generated by Django 6.0 on 2025-12-20 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns the fridge', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fridges', related_query_name='fridge', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fridge',
                'verbose_name_plural': 'Fridges',
                'ordering': ('name',),
            },
        ),
    ]
