# Generated by Django 6.0 on 2025-12-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridge',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
