# Generated by Django 6.0 on 2025-12-23 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0002_alter_fridge_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridge',
            name='owner',
            field=models.ForeignKey(help_text='User who owns the fridge', on_delete=django.db.models.deletion.CASCADE, related_name='fridges', related_query_name='fridge', to=settings.AUTH_USER_MODEL),
        ),
    ]
