# Generated by Django 6.0 on 2025-12-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0003_alter_fridge_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridge',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
