# Generated by Django 6.0 on 2025-12-27 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0007_alter_product_measurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='FridgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fridge', models.ForeignKey(help_text='Fridge inside which is the item', on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='item', to='fridge.fridge')),
                ('product', models.ForeignKey(help_text='Product f which type is the item', on_delete=django.db.models.deletion.CASCADE, related_name='fridge_items', related_query_name='fridge_item', to='fridge.product')),
            ],
            options={
                'verbose_name': 'Fridge Item',
                'verbose_name_plural': 'Fridge Items',
                'ordering': ('product__name',),
                'constraints': [models.UniqueConstraint(fields=('fridge', 'product'), name='unique_product_in_fridge')],
            },
        ),
    ]
