# Generated by Django 6.0 on 2025-12-27 11:18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0008_fridgeitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
