# Generated by Django 6.0 on 2025-12-27 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0009_alter_fridgeitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeitem',
            name='product',
            field=models.ForeignKey(help_text='Product of which type is the item', on_delete=django.db.models.deletion.CASCADE, related_name='fridge_items', related_query_name='fridge_item', to='fridge.product'),
        ),
    ]
