# Generated by Django 6.0 on 2025-12-27 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0010_alter_fridgeitem_product'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fridgeitem',
            name='unique_product_in_fridge',
        ),
    ]
