# Generated by Django 6.0 on 2025-12-27 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0011_remove_fridgeitem_unique_product_in_fridge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FridgeMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('a', 'Admin'), ('m', 'Member')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fridge', models.ForeignKey(help_text='Membership to fridge', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', related_query_name='membership', to='fridge.fridge')),
                ('member', models.ForeignKey(help_text='User is the member', on_delete=django.db.models.deletion.CASCADE, related_name='members', related_query_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
