# Generated by Django 6.0 on 2025-12-27 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0012_fridgemembers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fridgemembers',
            options={'ordering': ('fridge__name',), 'verbose_name': 'Fridge member', 'verbose_name_plural': 'Fridge members'},
        ),
        migrations.AlterField(
            model_name='fridgemembers',
            name='fridge',
            field=models.ForeignKey(help_text='Membership to fridge', on_delete=django.db.models.deletion.CASCADE, related_name='fridge_memberships', related_query_name='fridge_membership', to='fridge.fridge'),
        ),
        migrations.AlterField(
            model_name='fridgemembers',
            name='member',
            field=models.ForeignKey(help_text='User is the member', on_delete=django.db.models.deletion.CASCADE, related_name='fridge_memberships', related_query_name='fridge_membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fridgemembers',
            name='role',
            field=models.CharField(choices=[('a', 'Admin'), ('m', 'Member')], default='m', max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='fridgemembers',
            unique_together={('fridge', 'member')},
        ),
    ]
